////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated. 
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace kawaiWeb {
    
    
//    public partial class CadastroPerfil {
        
//        /// <summary>
//        /// txtCodigo control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox txtCodigo;
        
//        /// <summary>
//        /// txtServico control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox txtServico;
        
//        /// <summary>
//        /// txtValor control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.TextBox txtValor;
        
//        /// <summary>
//        /// btnSalvar control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnSalvar;
        
//        /// <summary>
//        /// btnCancelar control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
//        /// <summary>
//        /// gvLista control.
//        /// </summary>
//        /// <remarks>
//        /// Auto-generated field.
//        /// To modify move field declaration from designer file to code-behind file.
//        /// </remarks>
//        protected global::System.Web.UI.WebControls.GridView gvLista;
//    }
//}
